create table if not exists public.menu_items (id bigint generated by default as identity primary key, category text not null, name text not null, description text default '', price text default '', active boolean default true, sort_order integer default 0);

alter table public.menu_items enable row level security;

create policy "public read active" on public.menu_items for select to anon,authenticated using (active=true);

create policy "admins insert" on public.menu_items for insert to authenticated with check (true);

create policy "admins update" on public.menu_items for update to authenticated using (true) with check (true);

create policy "admins delete" on public.menu_items for delete to authenticated using (true);

insert into public.menu_items (category,name,description,price,active,sort_order) values
('مطبوخات ومشاوي','مناسف فروج','', '', true, 0),
('مطبوخات ومشاوي','كبسة بالفروج','', '', true, 1),
('مطبوخات ومشاوي','كفتة مشوية بالفرن','', '', true, 2),
('مطبوخات ومشاوي','كفتة هندية','', '', true, 3),
('مطبوخات ومشاوي','مقلوبة بتنجان','', '', true, 4),
('مطبوخات ومشاوي','صينية فروج بالفرن','', '', true, 5),
('مطبوخات ومشاوي','منسف ماندي مع فريكة','', '', true, 6),
('مطبوخات ومشاوي','مسقعة بندورة','', '', true, 7),
('مطبوخات ومشاوي','مشاوي كباب لحمة','', '', true, 8),
('مطبوخات ومشاوي','مشاوي كباب فروج','', '', true, 9),
('مطبوخات ومشاوي','فتة حمص','', '', true, 10),
('مطبوخات ومشاوي','فول متبل','', '', true, 11),
('مطبوخات ومشاوي','فتة مكدوس بالفرن','', '', true, 12),
('مطبوخات ومشاوي','صحن حمص','', '', true, 13),
('مطبوخات ومشاوي','فتوش','', '', true, 14),
('مطبوخات ومشاوي','سلطة خضار','', '', true, 15),
('مطبوخات ومشاوي','تبولة','', '', true, 16),
('مطبوخات ومشاوي','تبلة','', '', true, 17),
('مطبوخات ومشاوي','كبة نية','', '', true, 18),
('مطبوخات ومشاوي','كبة مشوية','', '', true, 19),
('مطبوخات ومشاوي','مَدّة لحمة بصينية','', '', true, 20),
('السندويشات','سندويش كباب فروج','', '', true, 21),
('السندويشات','سندويش لحمة','', '', true, 22),
('السندويشات','سندويش بطاطا','', '', true, 23),
('السندويشات','سندويش فلافل','', '', true, 24),
('الوجبات السريعة','إندومي','', '', true, 25),
('المشروبات الباردة','عصير طبيعي','', '', true, 26),
('المشروبات الباردة','مشروبات غازية','', '', true, 27),
('المشروبات الباردة','مشروبات طاقة','', '', true, 28),
('المشروبات الباردة','مياه معدنية','', '', true, 29),
('المشروبات الساخنة','قهوة عربية','', '', true, 30),
('المشروبات الساخنة','قهوة إكسبريس','', '', true, 31),
('المشروبات الساخنة','شاي','', '', true, 32),
('المشروبات الساخنة','شاي بالنعناع','', '', true, 33),
('المشروبات الساخنة','زهورات','', '', true, 34),
('المشروبات الساخنة','نسكافيه','', '', true, 35),
('المشروبات الساخنة','كابتشينو','', '', true, 36),
('المشروبات الساخنة','ميلو','', '', true, 37);